In [2]:
print("Hello, Python World!")

Hello, Python World!


In [8]:
%run main.py

Hello, Python World!


In [4]:
x = 5
X = 4

In [5]:
X

4

In [9]:
# This is a single-line comment

print("Hello")  # This is an inline comment

'''
This is a multi-line comment or docstring.
It can span multiple lines.
Useful for documentation.
'''

Hello


'\nThis is a multi-line comment or docstring.\nIt can span multiple lines.\nUseful for documentation.\n'

In [10]:
type(X)

int

In [11]:
_isactive = True

In [13]:
if _isactive:
    print('1')

1


In [ ]:
# global variable
x = 10



In [14]:
print(globals())

{'__name__': '__main__', '__doc__': 'Module created for script run in IPython', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', 'print("Hello, Python World!")', 'print("Hello, Python World!")', "get_ipython().run_line_magic('run', 'main.py')", 'x = 5\nX = 4', 'X', "get_ipython().run_line_magic('run', 'Main.py')", "get_ipython().run_line_magic('run', 'MOin.py')", "get_ipython().run_line_magic('run', 'mAin.py')", '# This is a single-line comment\n\nprint("Hello")  # This is an inline comment\n\n\'\'\'\nThis is a multi-line comment or docstring.\nIt can span multiple lines.\nUseful for documentation.\n\'\'\'', 'type(X)', '_isactive = True', "if _isactive then print('1')", "if _isactive:\n    print('1')", 'print(globals())'], '_oh': {5: 4, 9: '\nThis is a multi-line comment or docstring.\nIt can span multiple lines.\nUseful for documentation.\n', 10: <class 'int'>}, '_dh': 

In [27]:
x = int(3.7)          # Converts float 3.7 to integer 3
y = float("4.2")     # Converts string to float
z = str(10)           # Converts integer to string
print(x, y, z)

3 4.2 10


In [15]:
y = float("4.2")

In [16]:
y

4.2

In [17]:
z = 10

In [18]:
type(z)

int

In [20]:
z = str(z)

In [21]:
z

'10'

In [25]:
# concat string
str(y) + z

'4.210'

In [23]:
name = 'abc'
age = 30

In [24]:
# concat string
name + ' ' + str(age)

'abc 30'

In [28]:
x

3

In [29]:
x = 66
y = 456

In [30]:
x > y

False

In [31]:
x == y

False

In [33]:
x > y or x > 0

True

In [37]:
y > x and y != 2

True

In [39]:
y/x

6.909090909090909

In [40]:
# modulus
y//x

6

In [41]:
# remainder
y%x

60

## List

In [56]:
# Creating a list
fruits = ["apple", "banana", "cherry"]

In [58]:
fruits.insert(1,'mango')

In [61]:
len(fruits)

4

In [65]:
fruits[::-1]

['cherry', 'banana', 'mango', 'apple']

In [54]:
fruits.pop(1)

'banana'

In [55]:
fruits

['apple', 'cherry']

In [ ]:
# Adding an item
fruits.append("orange")

# Inserting an item at index 1
fruits.insert(1, "mango")

# Removing an item
fruits.remove("banana")

# Accessing elements
print("First item:", fruits[0])

# Slicing
print("First two items:", fruits[:2])

# Length of the list
print("Length:", len(fruits))

# Display the final list
print("Updated list:", fruits)

In [ ]:
# Basic slicing examples
text = "Python"

print("text[:]       =>", text[:])       # Copy the whole sequence
print("text[0:2]     =>", text[0:2])     # Subsequence from index 0 to 1
print("text[2:]      =>", text[2:])      # From index 2 to the end
print("text[:4]      =>", text[:4])      # From beginning to index 3
print("text[::]      =>", text[::])      # Full copy (same as [:])
print("text[::2]     =>", text[::2])     # Every second character
print("text[::-1]    =>", text[::-1])    # Reverse the sequence

In [66]:
# Creating tuples
t1 = (1, 2, 3)
t2 = 4, 5, 6           # parentheses optional




In [67]:
print("t1:", t1)

t1: (1, 2, 3)


In [68]:
print("t2:", t2)

t2: (4, 5, 6)


In [72]:
single = (42,) 

In [73]:
single

(42,)

In [74]:
empty = ()

In [75]:
type(empty)

tuple

In [ ]:
# Indexing and slicing
print("t1[0]:", t1[0])
print("t1[-1]:", t1[-1])
print("t1[1:3]:", t1[1:3])

# Tuple unpacking
x, y, z = t1
print("Unpacked:", x, y, z)

# Concatenation and repetition
print("t1 + t2:", t1 + t2)
print("t1 * 2:", t1 * 2)

# Membership test
print("2 in t1:", 2 in t1)
print("99 in t1:", 99 in t1)

# Nested tuple with mutable object
nested = (1, [10, 20], 3)
print("Before:", nested)
nested[1].append(30)   # allowed because list is mutable
print("After:", nested)

# Length of tuple
print("Length of t1:", len(t1))

In [ ]:
# set(a difference b) = numbers in a but not in b
# set(b difference a) = numbers in b but not in a

In [76]:
# Creating a dictionary
person = {"name": "Alice", "age": 30}
print("Initial:", person)



Initial: {'name': 'Alice', 'age': 30}


In [77]:
person.items()

dict_items([('name', 'Alice'), ('age', 30)])

In [ ]:
# Accessing values
print("Name:", person["name"])

# Updating a value
person["age"] = 31

# Adding a new key-value pair
person["city"] = "Kuala Lumpur"
print("After update:", person)

# Getting keys, values, items
print("Keys:", list(person.keys()))
print("Values:", list(person.values()))
print("Items:", list(person.items()))

# Membership test
print("Has 'age'?", "age" in person)
print("Has 'salary'?", "salary" in person)

# Removing a key
del person["city"]
print("After removing city:", person)

# Using pop with default
age = person.pop("age", None)
print("Popped age:", age)
print("After pop:", person)

In [80]:
i = 0
while i in range(0,2):
    i = i + 1
    print(i)
    

1
2


In [91]:
def greet(name):
    # code block
    name = str(name)
    return f"Hello {name}"

In [94]:
greet('abc')

'Hello abc'

In [101]:
from datetime import datetime, date, time, timedelta

In [102]:

now = datetime.now()


In [104]:
print(now.strftime("%Y-%m-%d %H:%M:%S"))
print(now.strftime("%Y"))

2025-09-29 12:39:41
2025


In [106]:
name = input("Enter your name: ")
print("Hello,", name)
print(f"Hello, {name}")

Enter your name:  abc


Hello, abc
Hello, abc


In [111]:
age = int(input("Enter your age: "))


Enter your age:  30


In [112]:
type(age)

int

In [ ]:
try:
    num = int("abc")
    print(100 / num)
except ZeroDivisionError:
    print(" Cannot divide by zero!")
except ValueError:
    print(" Invalid number format!")

In [114]:
file = open("data.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'data.txt'

In [115]:
try:
    file = open("data.txt")
    print(file.read())
except FileNotFoundError:
    print(" File not found!")
finally:
    print(" Closing resources (if open).")

 File not found!
 Closing resources (if open).


In [116]:
try:
    risky_code()
except Exception as e:
    print("⚠️ Something went wrong:", e)

⚠️ Something went wrong: name 'risky_code' is not defined


In [117]:
count = 0

def update():
    count += 1  # Error! Python thinks count is local
    print(count)

In [118]:
update()

UnboundLocalError: cannot access local variable 'count' where it is not associated with a value

In [119]:
f = open("data\myfile.txt", "a")
f.write("\nMore text.")  # Appends without erasing content
f.close()

In [121]:
f = open("data/newfile.txt", "x")
f.write("This is a new file.")  # Only works if file does not exist
f.close()

In [122]:
import glob
files = glob.glob("data/*.txt")

for file in files:
    with open(file, "r") as f:
        print(f"Contents of {file}:")
        print(f.read())

Contents of data\myfile.txt:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac leo euismod, eleifend lorem a, fringilla neque. Suspendisse consectetur sapien at congue suscipit. Morbi nisi est, ornare et lacinia in, finibus sed diam. Duis semper vel felis in tempus. In et cursus nibh. Nullam accumsan ante elit, accumsan malesuada mauris faucibus nec. Mauris faucibus ornare neque, non viverra dui posuere non. Donec feugiat neque id eros tristique ornare. Duis vel nisi quam. In vehicula urna non elit hendrerit, volutpat gravida lectus faucibus. Nunc tempus malesuada turpis, sagittis suscipit odio maximus nec. Sed eu pharetra sapien. Fusce convallis ipsum quis rutrum dignissim. Duis dictum, magna eget porta vulputate, ipsum ligula mollis neque, et egestas nisl nulla dictum tellus. Ut sed libero dolor.
More text.
Contents of data\newfile.txt:
This is a new file.


In [124]:
import re
text = "Contact: alice@example.com, bob@domain.org,myname"
emails = re.findall(r"[\w.-]+@[\w.-]+", text)
print(emails)  # Extracts all emails

['alice@example.com', 'bob@domain.org']


In [127]:
import numpy as np
print("Zeros (2x3):\n", np.zeros((2,2, 3)))


Zeros (2x3):
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
